version: "3"

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "True"
      ALLOWED_HOSTS: "209.97.143.113"

  db:
    image: "nouchka/sqlite3"
    volumes:
      - db_data:/var/lib/sqlite/data

volumes:
  db_data:

