apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-django-app
  template:
    metadata:
      labels:
        app: my-django-app
    spec:
      containers:
        - name: my-django-app
          image: bennieo/django_app
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: sqlite
              mountPath: /commerce/db.sqlite3
      volumes:
        - name: django-settings-volume
          configMap:
            name: django-settings
      # volumes:
      #   - name: sqlite
      #     emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-django-app
spec:
  selector:
    app: my-django-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
         