apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: bennieo/django_app
        env:
        - name: DATABASE_URL
          value: "sqlite:///db.sqlite3"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: djan
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort
